---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 光子.
--- DateTime: 2022/4/8 9:50
---
---
--优惠券id
local voucherId = ARGV[1]
--用于id
local userId = ARGV[2]
--数据key
--库存key
local stockKey = 'seckill:stock:' .. voucherId
--订单key
local orderKey = 'seckill:order' .. voucherId

--脚本业务
--判断库存是否充足
if(tonumber(redis.call('get'),stockKey)<=0) then
    --不足 返回1
    return 1
end

--判断是否下单
if (redis.call('sismember',orderKey,userId) == 1) then
    --存在 返回2
    return 2
end

--扣减库存
redis.call('incrby',stockKey,-1)
--下单
redis.call('sadd',stockKey,userId)
return 0
